version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
  virtuoso:
    ports:
      - "8890:8890"
  authentication:    
    ports:
        - 8888:80
        - 9229:9229
    environment:
      NODE_ENV: "development"
    volumes:
      - /Users/siebe/Documents/Work/RedPencil.io/veeakker/mu-node-authentication-service/:/app/