DELETE {
  GRAPH  <http://mu.semte.ch/application> {
    ?s ?p ?o .
  }
} INSERT {
  GRAPH  <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH  <http://mu.semte.ch/application> {
    ?s a ?type ; ?p ?o .
    VALUES ?type {
                        <http://veeakker.be/vocabularies/shop/DeliveryPlace>
                        <http://schema.org/Organization>
                        <http://veeakker.be/vocabularies/shop/DeliveryKind>
                        <http://schema.org/GeoCoordinate>
                        <http://schema.org/PostalAddress>
                        <http://veeakker.be/vocabularies/shop/ProductGroup>
                        <http://schema.org/Product>
                        <http://purl.org/goodrelations/v1#Offering>
                        <http://purl.org/goodrelations/v1#UnitPriceSpecification>
                        <http://purl.org/goodrelations/v1#QuantitativeValue>
                        <http://purl.org/goodrelations/v1#TypeAndQuantityNode>
                        <http://veeakker.be/vocabularies/shop/Basket>
                        <http://veeakker.be/vocabularies/shop/OrderLine>
                        <http://veeakker.be/vocabularies/shop/SpotlightProduct>
                        <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject>
    }
  }
}

