PREFIX veeakker: <http://veeakker.be/vocabularies/shop/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE { GRAPH ?g { ?s veeakker:isEnabled ?enabled. } }
WHERE {
  GRAPH ?g {
    ?s a gr:Offering; veeakker:isEnabled ?enabled.
  }
};
INSERT {
  GRAPH ?g {
    ?s veeakker:isEnabled ?enabled.
  }
} WHERE {
  GRAPH ?g {
    ?s a gr:Offering.
    BIND ( true AS ?enabled )
  }
}
