(in-package :mu-cl-resources)

(define-resource account ()
  :class (s-prefix "foaf:OnlineAccount")
  :properties `((:email :string ,(s-prefix "account:email"))
                (:first-name :string ,(s-prefix "foaf:firstName"))
                (:last-name :string ,(s-prefix "foaf:familyName")))
  :has-one `((postal-address :via ,(s-prefix "schema:PostalAddress")
                             :as "postal-address"))
  :resource-base (s-url "http://mu.semte.ch/vocabularies/accounts/")
  :on-path "accounts")
